### ISSUE TITLE
Crear proyecto MVC

### ISSUE THREAD

**Issue by GitHub-Adel** [GitHub-Adel/NetCoreMVC#4]
inicio
1) abrir vscode
2) abrir la terminal de vscode
3) cd RutaDirectorioProyecto
4) dotnet new mvc -n NombreProyecto
5) ir al directorio y arrastrarlo a vscode.
6) instalar complemento c# para intelillent
7) dotnet run - arranca el servicio
8) copiar url y pegar en el navegador - muestra la pagina
9) ctrl + c , detiene el servicio.
fin

**Comment by desarrollador-prueba** [comment]
creado
