### ISSUE TITLE
Controladores

### ISSUE THREAD

**Issue by GitHub-Adel** [GitHub-Adel/NetCoreMVC#5]
inicio

public class NombrevistaController  : Controller
{
       public TipoDevuelto NombreMetodo()
       {
           return ValorDevuelto;
       }

       public TipoDevuelto NombreMetodo(string id)
       {
           return id;
       }
}

1) la vista y el modelo se comunican a través del controlador. 
2) es una clase nombrada NombrevistaController
3) hereda de la clase Controller
4) cada vista tiene un controlador.
5) cada acción de la vista llama un metodo del controlador

https://localhost:50001/Vista/NombreMetodo
------------------------------------------------------
6) ejecuta el metodo  NombreMetodo del controlador 
    VistaController este metodo no  recibe parametro.

https://localhost:50001/Vista/NombreMetodo/?Nombreparametro=valor
------------------------------------------------------
7) ejecuta el metodo  NombreMetodo del controlador 
    VistaController este metodo recibe un parametro.

8) el tipovalorDevuelto siempre termina en Result. ya que
    hay unos cuantos tipos predefinido para devolver que son 
    interfaces ej:  ITipoResult,  si para el valor a retornar 
    no hay un tipo entonces se usa IActionResult.

fin

**Comment by desarrollador-prueba** [comment]
completado issue#5
